"""Domain models (immutable value objects)."""

from sie.domain.models.content import (
    ContentAnalysisConfig,
    ContentComparison,
    ContentMetrics,
    ContentQualityReport,
    ContentType,
    DuplicateStatus,
    FreshnessAnalysis,
    HeadingAnalysis,
    ImageAnalysis,
    KeywordDensity,
    LinkAnalysis,
    MultimediaAnalysis,
    QualityTier,
    ReadabilityMetrics,
    StructuredDataAnalysis,
)
from sie.domain.models.crawl import (
    CrawlPageRecord,
    CrawlPolicy,
    CrawlRunRecord,
    CrawlStats,
    CrawlStatus,
    CrawlTarget,
)
from sie.domain.models.diagnosis import (
    DiagnosisCategory,
    DiagnosisEvidence,
    DiagnosisIssue,
    DiagnosisPriority,
    DiagnosisResult,
    DiagnosisSeverity,
)
from sie.domain.models.events import CrawlEvent, CrawlFinished, ErrorOccurred, PageFetchCompleted
from sie.domain.models.page import FetchedPage, RenderedPage
from sie.domain.models.search import (
    CompetitorRanking,
    RankingObservation,
    SearchDataset,
    SearchDevice,
    SearchIntent,
    SearchKeyword,
    SearchQuery,
)
from sie.domain.models.search_import import SearchImportResult, SearchRecordError
from sie.domain.models.search_validation import (
    DatasetValidationIssue,
    DatasetValidationResult,
    SearchDatasetContent,
)

__all__ = [
    "CompetitorRanking",
    "ContentAnalysisConfig",
    "ContentComparison",
    "ContentMetrics",
    "ContentQualityReport",
    "ContentType",
    "CrawlEvent",
    "CrawlFinished",
    "CrawlPageRecord",
    "CrawlPolicy",
    "CrawlRunRecord",
    "CrawlStats",
    "CrawlStatus",
    "CrawlTarget",
    "DatasetValidationIssue",
    "DatasetValidationResult",
    "DiagnosisCategory",
    "DiagnosisEvidence",
    "DiagnosisIssue",
    "DiagnosisPriority",
    "DiagnosisResult",
    "DiagnosisSeverity",
    "DuplicateStatus",
    "ErrorOccurred",
    "FetchedPage",
    "FreshnessAnalysis",
    "HeadingAnalysis",
    "ImageAnalysis",
    "KeywordDensity",
    "LinkAnalysis",
    "MultimediaAnalysis",
    "PageFetchCompleted",
    "QualityTier",
    "RankingObservation",
    "ReadabilityMetrics",
    "RenderedPage",
    "SearchDataset",
    "SearchDatasetContent",
    "SearchDevice",
    "SearchImportResult",
    "SearchIntent",
    "SearchKeyword",
    "SearchQuery",
    "SearchRecordError",
    "StructuredDataAnalysis",
]
