"""Add html_content column to crawl_pages

Revision ID: 5e4c59abfe15
Revises: 123456789abc
Create Date: 2026-08-26 05:15:22.725638

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e4c59abfe15"
down_revision: str | None = "123456789abc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crawl_pages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("html_content", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crawl_pages", schema=None) as batch_op:
        batch_op.drop_column("html_content")
    # ### end Alembic commands ###
