"""Add content intelligence tables

Revision ID: 741e30c9a8f0
Revises: 0002
Create Date: 2026-08-24 02:51:01.713807

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "741e30c9a8f0"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_comparisons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("url_a", sa.Text(), nullable=False),
        sa.Column("url_b", sa.Text(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column("jaccard_similarity", sa.Float(), nullable=False),
        sa.Column("cosine_similarity", sa.Float(), nullable=False),
        sa.Column("word_overlap_count", sa.Integer(), nullable=False),
        sa.Column("word_overlap_ratio", sa.Float(), nullable=False),
        sa.Column("structural_similarity", sa.Float(), nullable=False),
        sa.Column("duplicate_status", sa.String(length=32), nullable=False),
        sa.Column("compared_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("content_comparisons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_content_comparisons_run_id"), ["run_id"], unique=False)

    op.create_table(
        "content_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("visible_text", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("unique_word_count", sa.Integer(), nullable=False),
        sa.Column("type_token_ratio", sa.Float(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("paragraph_count", sa.Integer(), nullable=False),
        sa.Column("avg_words_per_sentence", sa.Float(), nullable=False),
        sa.Column("avg_sentences_per_paragraph", sa.Float(), nullable=False),
        sa.Column("stopword_ratio", sa.Float(), nullable=False),
        sa.Column("html_to_text_ratio", sa.Float(), nullable=False),
        sa.Column("readability", sa.JSON(), nullable=False),
        sa.Column("headings", sa.JSON(), nullable=False),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.Column("links", sa.JSON(), nullable=False),
        sa.Column("structured_data", sa.JSON(), nullable=False),
        sa.Column("freshness", sa.JSON(), nullable=False),
        sa.Column("multimedia", sa.JSON(), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("quality_tier", sa.String(length=16), nullable=False),
        sa.Column("thin_content", sa.Integer(), nullable=False),
        sa.Column("extracted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("content_metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_content_metrics_run_id"), ["run_id"], unique=False)

    op.create_table(
        "content_quality_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=False),
        sa.Column("analyzed_pages", sa.Integer(), nullable=False),
        sa.Column("avg_quality_score", sa.Float(), nullable=False),
        sa.Column("quality_distribution", sa.JSON(), nullable=False),
        sa.Column("thin_content_pages", sa.JSON(), nullable=False),
        sa.Column("duplicate_groups", sa.JSON(), nullable=False),
        sa.Column("top_issues", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("content_quality_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_content_quality_reports_run_id"), ["run_id"], unique=True
        )

    with op.batch_alter_table("crawl_pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crawl_pages_url"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crawl_pages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crawl_pages_url"), ["url"], unique=False)

    with op.batch_alter_table("content_quality_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_quality_reports_run_id"))

    op.drop_table("content_quality_reports")
    with op.batch_alter_table("content_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_metrics_run_id"))

    op.drop_table("content_metrics")
    with op.batch_alter_table("content_comparisons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_comparisons_run_id"))

    op.drop_table("content_comparisons")
    # ### end Alembic commands ###
